// Realistic seed data for the SkillPath knowledge graph.
// Skills form a DAG via PREREQUISITE_OF edges; courses TEACH and REQUIRE
// skills; learners HAS_SKILL and COMPLETED courses.

const skills = [
  {
    id: "sk_programming_basics",
    name: "Programming Basics",
    category: "Foundations",
    description:
      "Variables, control flow, functions, and how to reason about a program.",
  },
  {
    id: "sk_data_structures",
    name: "Data Structures",
    category: "Foundations",
    description: "Arrays, lists, stacks, queues, trees, and hash maps.",
  },
  {
    id: "sk_algorithms",
    name: "Algorithms",
    category: "Foundations",
    description: "Sorting, searching, recursion, and complexity analysis.",
  },
  {
    id: "sk_git",
    name: "Git & Version Control",
    category: "Foundations",
    description: "Branching, merging, and collaborating on a shared codebase.",
  },
  {
    id: "sk_html_css",
    name: "HTML & CSS",
    category: "Web",
    description: "Structuring and styling pages for the browser.",
  },
  {
    id: "sk_javascript",
    name: "JavaScript",
    category: "Web",
    description: "The core language of interactive web pages.",
  },
  {
    id: "sk_typescript",
    name: "TypeScript",
    category: "Web",
    description: "Static typing on top of JavaScript for larger codebases.",
  },
  {
    id: "sk_react",
    name: "React",
    category: "Web",
    description: "Building component-based user interfaces.",
  },
  {
    id: "sk_nodejs",
    name: "Node.js",
    category: "Web",
    description: "Running JavaScript on the server.",
  },
  {
    id: "sk_rest_apis",
    name: "REST APIs",
    category: "Web",
    description: "Designing and consuming HTTP APIs.",
  },
  {
    id: "sk_system_design",
    name: "System Design",
    category: "Systems",
    description:
      "Designing services that scale, fail gracefully, and stay maintainable.",
  },
  {
    id: "sk_sql",
    name: "SQL",
    category: "Data",
    description: "Querying and manipulating relational data.",
  },
  {
    id: "sk_data_modeling",
    name: "Data Modeling",
    category: "Data",
    description: "Shaping data for how it will actually be queried.",
  },
  {
    id: "sk_databases",
    name: "Databases",
    category: "Systems",
    description: "How storage engines, indexes, and transactions work.",
  },
  {
    id: "sk_graph_databases",
    name: "Graph Databases",
    category: "Systems",
    description: "Modeling and querying densely connected data with Cypher.",
  },
  {
    id: "sk_distributed_systems",
    name: "Distributed Systems",
    category: "Systems",
    description: "Consistency, replication, and failure across many machines.",
  },
  {
    id: "sk_python_ds",
    name: "Python for Data Science",
    category: "Data",
    description: "Using Python and its data libraries for analysis.",
  },
  {
    id: "sk_statistics",
    name: "Statistics",
    category: "Data",
    description: "Distributions, hypothesis testing, and inference.",
  },
  {
    id: "sk_ml_basics",
    name: "Machine Learning Basics",
    category: "AI",
    description: "Supervised and unsupervised learning fundamentals.",
  },
  {
    id: "sk_deep_learning",
    name: "Deep Learning",
    category: "AI",
    description: "Neural networks, backpropagation, and training at scale.",
  },
  {
    id: "sk_nlp",
    name: "Natural Language Processing",
    category: "AI",
    description: "Teaching models to work with human language.",
  },
  {
    id: "sk_linux",
    name: "Linux Basics",
    category: "DevOps",
    description: "The shell, processes, and file system fundamentals.",
  },
  {
    id: "sk_docker",
    name: "Docker",
    category: "DevOps",
    description: "Packaging applications into portable containers.",
  },
  {
    id: "sk_cicd",
    name: "CI/CD",
    category: "DevOps",
    description: "Automating build, test, and release pipelines.",
  },
  {
    id: "sk_cloud_fundamentals",
    name: "Cloud Fundamentals",
    category: "DevOps",
    description: "Compute, storage, and networking in a public cloud.",
  },
  {
    id: "sk_kubernetes",
    name: "Kubernetes",
    category: "DevOps",
    description: "Orchestrating containers at scale.",
  },
  {
    id: "sk_data_viz",
    name: "Data Visualization",
    category: "Data",
    description: "Turning data into charts people can actually act on.",
  },
  {
    id: "sk_ui_design",
    name: "UI Design Basics",
    category: "Design",
    description: "Layout, type, and color for digital interfaces.",
  },
  {
    id: "sk_ux_research",
    name: "UX Research",
    category: "Design",
    description: "Learning what users actually need before you build it.",
  },
  {
    id: "sk_design_systems",
    name: "Design Systems",
    category: "Design",
    description:
      "Reusable components and rules that keep a product consistent.",
  },
];

// [fromSkillId, toSkillId] meaning fromSkill is a PREREQUISITE_OF toSkill.
const prereqEdges = [
  ["sk_programming_basics", "sk_data_structures"],
  ["sk_data_structures", "sk_algorithms"],
  ["sk_programming_basics", "sk_git"],
  ["sk_programming_basics", "sk_html_css"],
  ["sk_html_css", "sk_javascript"],
  ["sk_javascript", "sk_typescript"],
  ["sk_javascript", "sk_react"],
  ["sk_javascript", "sk_nodejs"],
  ["sk_nodejs", "sk_rest_apis"],
  ["sk_rest_apis", "sk_system_design"],
  ["sk_algorithms", "sk_system_design"],
  ["sk_programming_basics", "sk_sql"],
  ["sk_sql", "sk_data_modeling"],
  ["sk_data_modeling", "sk_databases"],
  ["sk_databases", "sk_graph_databases"],
  ["sk_databases", "sk_distributed_systems"],
  ["sk_system_design", "sk_distributed_systems"],
  ["sk_programming_basics", "sk_python_ds"],
  ["sk_python_ds", "sk_statistics"],
  ["sk_statistics", "sk_ml_basics"],
  ["sk_ml_basics", "sk_deep_learning"],
  ["sk_deep_learning", "sk_nlp"],
  ["sk_git", "sk_linux"],
  ["sk_linux", "sk_docker"],
  ["sk_docker", "sk_cicd"],
  ["sk_docker", "sk_kubernetes"],
  ["sk_cicd", "sk_cloud_fundamentals"],
  ["sk_cloud_fundamentals", "sk_kubernetes"],
  ["sk_python_ds", "sk_data_viz"],
  ["sk_html_css", "sk_ui_design"],
  ["sk_ui_design", "sk_ux_research"],
  ["sk_ui_design", "sk_design_systems"],
];

const instructors = [
  {
    id: "in_amara",
    name: "Amara Chen",
    bio: "Backend engineer turned instructor, 10 years building distributed systems.",
  },
  {
    id: "in_leo",
    name: "Leo Martins",
    bio: "Frontend specialist and former design-systems lead.",
  },
  {
    id: "in_priya",
    name: "Priya Raman",
    bio: "Data scientist focused on applied statistics and ML.",
  },
  {
    id: "in_sofia",
    name: "Sofia Weber",
    bio: "DevOps consultant who has run infrastructure at three startups.",
  },
  {
    id: "in_daniel",
    name: "Daniel Osei",
    bio: "Database engineer and open-source contributor.",
  },
  {
    id: "in_maya",
    name: "Maya Iqbal",
    bio: "Product designer teaching research and UX fundamentals.",
  },
];

const courses = [
  {
    id: "co_intro_programming",
    title: "Intro to Programming",
    description: "Your first steps writing and reasoning about code.",
    level: "Beginner",
    durationHours: 12,
    provider: "SkillPath",
    url: "https://example.com/intro-programming",
    instructor: "in_amara",
    teaches: ["sk_programming_basics"],
    requires: [],
  },
  {
    id: "co_data_structures",
    title: "Data Structures That Matter",
    description: "The structures you will actually reach for on the job.",
    level: "Intermediate",
    durationHours: 10,
    provider: "SkillPath",
    url: "https://example.com/data-structures",
    instructor: "in_amara",
    teaches: ["sk_data_structures"],
    requires: ["sk_programming_basics"],
  },
  {
    id: "co_algorithms",
    title: "Algorithms in Practice",
    description:
      "Sorting, searching, and complexity, with real interview problems.",
    level: "Intermediate",
    durationHours: 14,
    provider: "SkillPath",
    url: "https://example.com/algorithms",
    instructor: "in_amara",
    teaches: ["sk_algorithms"],
    requires: ["sk_data_structures"],
  },
  {
    id: "co_git_essentials",
    title: "Git Essentials",
    description: "Branch, merge, and collaborate without fear.",
    level: "Beginner",
    durationHours: 4,
    provider: "SkillPath",
    url: "https://example.com/git",
    instructor: "in_sofia",
    teaches: ["sk_git"],
    requires: ["sk_programming_basics"],
  },
  {
    id: "co_html_css",
    title: "HTML & CSS Foundations",
    description: "Build and style your first real web pages.",
    level: "Beginner",
    durationHours: 8,
    provider: "SkillPath",
    url: "https://example.com/html-css",
    instructor: "in_leo",
    teaches: ["sk_html_css"],
    requires: ["sk_programming_basics"],
  },
  {
    id: "co_javascript",
    title: "Modern JavaScript",
    description: "The language behind every interactive web page.",
    level: "Beginner",
    durationHours: 16,
    provider: "SkillPath",
    url: "https://example.com/javascript",
    instructor: "in_leo",
    teaches: ["sk_javascript"],
    requires: ["sk_html_css"],
  },
  {
    id: "co_typescript",
    title: "TypeScript for JS Developers",
    description: "Add types to code you already know how to write.",
    level: "Intermediate",
    durationHours: 8,
    provider: "SkillPath",
    url: "https://example.com/typescript",
    instructor: "in_leo",
    teaches: ["sk_typescript"],
    requires: ["sk_javascript"],
  },
  {
    id: "co_react_fundamentals",
    title: "React Fundamentals",
    description: "Components, state, and the patterns behind modern UIs.",
    level: "Intermediate",
    durationHours: 14,
    provider: "SkillPath",
    url: "https://example.com/react",
    instructor: "in_leo",
    teaches: ["sk_react"],
    requires: ["sk_javascript"],
  },
  {
    id: "co_react_advanced",
    title: "Advanced React Patterns",
    description: "Performance, composition, and large-app architecture.",
    level: "Advanced",
    durationHours: 10,
    provider: "SkillPath",
    url: "https://example.com/react-advanced",
    instructor: "in_leo",
    teaches: ["sk_react", "sk_design_systems"],
    requires: ["sk_react"],
  },
  {
    id: "co_nodejs",
    title: "Node.js from Scratch",
    description: "Run JavaScript on the server and talk to a database.",
    level: "Intermediate",
    durationHours: 12,
    provider: "SkillPath",
    url: "https://example.com/nodejs",
    instructor: "in_amara",
    teaches: ["sk_nodejs"],
    requires: ["sk_javascript"],
  },
  {
    id: "co_rest_apis",
    title: "Designing REST APIs",
    description: "Resource modeling, versioning, and real-world API design.",
    level: "Intermediate",
    durationHours: 8,
    provider: "SkillPath",
    url: "https://example.com/rest-apis",
    instructor: "in_amara",
    teaches: ["sk_rest_apis"],
    requires: ["sk_nodejs"],
  },
  {
    id: "co_system_design",
    title: "System Design Interview Prep",
    description: "Design services that scale, from first principles.",
    level: "Advanced",
    durationHours: 16,
    provider: "SkillPath",
    url: "https://example.com/system-design",
    instructor: "in_daniel",
    teaches: ["sk_system_design"],
    requires: ["sk_rest_apis", "sk_algorithms"],
  },
  {
    id: "co_distributed_systems",
    title: "Distributed Systems Foundations",
    description: "Consistency, replication, and the CAP theorem in practice.",
    level: "Advanced",
    durationHours: 16,
    provider: "SkillPath",
    url: "https://example.com/distributed-systems",
    instructor: "in_daniel",
    teaches: ["sk_distributed_systems"],
    requires: ["sk_system_design"],
  },
  {
    id: "co_sql_essentials",
    title: "SQL Essentials",
    description: "Query and shape relational data with confidence.",
    level: "Beginner",
    durationHours: 8,
    provider: "SkillPath",
    url: "https://example.com/sql",
    instructor: "in_daniel",
    teaches: ["sk_sql"],
    requires: ["sk_programming_basics"],
  },
  {
    id: "co_data_modeling",
    title: "Data Modeling for Applications",
    description: "Model data for how it is actually going to be queried.",
    level: "Intermediate",
    durationHours: 8,
    provider: "SkillPath",
    url: "https://example.com/data-modeling",
    instructor: "in_daniel",
    teaches: ["sk_data_modeling"],
    requires: ["sk_sql"],
  },
  {
    id: "co_databases_internals",
    title: "How Databases Work",
    description: "Storage engines, indexes, and transactions under the hood.",
    level: "Advanced",
    durationHours: 12,
    provider: "SkillPath",
    url: "https://example.com/databases",
    instructor: "in_daniel",
    teaches: ["sk_databases"],
    requires: ["sk_data_modeling"],
  },
  {
    id: "co_graph_databases",
    title: "Graph Databases & Cypher",
    description: "Model and query densely connected data.",
    level: "Intermediate",
    durationHours: 10,
    provider: "SkillPath",
    url: "https://example.com/graph-databases",
    instructor: "in_daniel",
    teaches: ["sk_graph_databases"],
    requires: ["sk_databases"],
  },
  {
    id: "co_python_ds",
    title: "Python for Data Science",
    description: "Analyze real datasets with Python, pandas, and numpy.",
    level: "Beginner",
    durationHours: 12,
    provider: "SkillPath",
    url: "https://example.com/python-ds",
    instructor: "in_priya",
    teaches: ["sk_python_ds"],
    requires: ["sk_programming_basics"],
  },
  {
    id: "co_statistics",
    title: "Statistics for Data Science",
    description: "The statistics you actually need before modeling.",
    level: "Intermediate",
    durationHours: 12,
    provider: "SkillPath",
    url: "https://example.com/statistics",
    instructor: "in_priya",
    teaches: ["sk_statistics"],
    requires: ["sk_python_ds"],
  },
  {
    id: "co_ml_basics",
    title: "Machine Learning Basics",
    description: "Supervised and unsupervised learning, from scratch.",
    level: "Intermediate",
    durationHours: 16,
    provider: "SkillPath",
    url: "https://example.com/ml-basics",
    instructor: "in_priya",
    teaches: ["sk_ml_basics"],
    requires: ["sk_statistics"],
  },
  {
    id: "co_deep_learning",
    title: "Deep Learning Foundations",
    description: "Neural networks and how to actually train them.",
    level: "Advanced",
    durationHours: 18,
    provider: "SkillPath",
    url: "https://example.com/deep-learning",
    instructor: "in_priya",
    teaches: ["sk_deep_learning"],
    requires: ["sk_ml_basics"],
  },
  {
    id: "co_nlp",
    title: "NLP in Practice",
    description: "Build systems that understand human language.",
    level: "Advanced",
    durationHours: 14,
    provider: "SkillPath",
    url: "https://example.com/nlp",
    instructor: "in_priya",
    teaches: ["sk_nlp"],
    requires: ["sk_deep_learning"],
  },
  {
    id: "co_data_viz",
    title: "Data Visualization",
    description: "Turn a spreadsheet into a chart someone can act on.",
    level: "Intermediate",
    durationHours: 6,
    provider: "SkillPath",
    url: "https://example.com/data-viz",
    instructor: "in_priya",
    teaches: ["sk_data_viz"],
    requires: ["sk_python_ds"],
  },
  {
    id: "co_linux",
    title: "Linux Basics",
    description:
      "The shell, processes, and files, for people who have never touched a terminal.",
    level: "Beginner",
    durationHours: 6,
    provider: "SkillPath",
    url: "https://example.com/linux",
    instructor: "in_sofia",
    teaches: ["sk_linux"],
    requires: ["sk_git"],
  },
  {
    id: "co_docker",
    title: "Docker for Developers",
    description: "Package an app once and run it anywhere.",
    level: "Intermediate",
    durationHours: 8,
    provider: "SkillPath",
    url: "https://example.com/docker",
    instructor: "in_sofia",
    teaches: ["sk_docker"],
    requires: ["sk_linux"],
  },
  {
    id: "co_cicd",
    title: "CI/CD Pipelines",
    description: "Automate the boring parts of shipping software.",
    level: "Intermediate",
    durationHours: 8,
    provider: "SkillPath",
    url: "https://example.com/cicd",
    instructor: "in_sofia",
    teaches: ["sk_cicd"],
    requires: ["sk_docker"],
  },
  {
    id: "co_cloud_fundamentals",
    title: "Cloud Fundamentals",
    description: "Compute, storage, and networking, cloud-agnostic.",
    level: "Beginner",
    durationHours: 10,
    provider: "SkillPath",
    url: "https://example.com/cloud",
    instructor: "in_sofia",
    teaches: ["sk_cloud_fundamentals"],
    requires: ["sk_cicd"],
  },
  {
    id: "co_kubernetes",
    title: "Kubernetes in Practice",
    description: "Orchestrate containers at scale, without the mystery.",
    level: "Advanced",
    durationHours: 14,
    provider: "SkillPath",
    url: "https://example.com/kubernetes",
    instructor: "in_sofia",
    teaches: ["sk_kubernetes"],
    requires: ["sk_docker", "sk_cloud_fundamentals"],
  },
  {
    id: "co_ui_design",
    title: "UI Design Basics",
    description: "Layout, type, and color for interfaces people enjoy using.",
    level: "Beginner",
    durationHours: 8,
    provider: "SkillPath",
    url: "https://example.com/ui-design",
    instructor: "in_maya",
    teaches: ["sk_ui_design"],
    requires: ["sk_html_css"],
  },
  {
    id: "co_ux_research",
    title: "UX Research Fundamentals",
    description: "Find out what users need before you build it.",
    level: "Intermediate",
    durationHours: 8,
    provider: "SkillPath",
    url: "https://example.com/ux-research",
    instructor: "in_maya",
    teaches: ["sk_ux_research"],
    requires: ["sk_ui_design"],
  },
  {
    id: "co_design_systems",
    title: "Building Design Systems",
    description:
      "Components and rules that keep a product consistent at scale.",
    level: "Advanced",
    durationHours: 10,
    provider: "SkillPath",
    url: "https://example.com/design-systems",
    instructor: "in_maya",
    teaches: ["sk_design_systems"],
    requires: ["sk_ui_design"],
  },
];

const learners = [
  { id: "le_jordan", name: "Jordan Blake" },
  { id: "le_priya_l", name: "Priya Nair" },
  { id: "le_marcus", name: "Marcus Webb" },
  { id: "le_hana", name: "Hana Kobayashi" },
  { id: "le_omar", name: "Omar Farouk" },
  { id: "le_ines", name: "Ines Duarte" },
];

// [learnerId, skillId]
const hasSkill = [
  ["le_jordan", "sk_programming_basics"],
  ["le_jordan", "sk_html_css"],
  ["le_jordan", "sk_javascript"],
  ["le_jordan", "sk_git"],
  ["le_priya_l", "sk_programming_basics"],
  ["le_priya_l", "sk_python_ds"],
  ["le_priya_l", "sk_statistics"],
  ["le_priya_l", "sk_sql"],
  ["le_marcus", "sk_programming_basics"],
  ["le_marcus", "sk_git"],
  ["le_marcus", "sk_linux"],
  ["le_marcus", "sk_docker"],
  ["le_hana", "sk_programming_basics"],
  ["le_hana", "sk_html_css"],
  ["le_hana", "sk_javascript"],
  ["le_hana", "sk_react"],
  ["le_hana", "sk_git"],
  ["le_omar", "sk_programming_basics"],
  ["le_omar", "sk_sql"],
  ["le_omar", "sk_data_modeling"],
  ["le_omar", "sk_databases"],
  ["le_ines", "sk_programming_basics"],
  ["le_ines", "sk_html_css"],
  ["le_ines", "sk_ui_design"],
];

// [learnerId, courseId]
const completed = [
  ["le_jordan", "co_intro_programming"],
  ["le_jordan", "co_html_css"],
  ["le_jordan", "co_javascript"],
  ["le_jordan", "co_git_essentials"],
  ["le_priya_l", "co_intro_programming"],
  ["le_priya_l", "co_python_ds"],
  ["le_priya_l", "co_statistics"],
  ["le_priya_l", "co_sql_essentials"],
  ["le_marcus", "co_intro_programming"],
  ["le_marcus", "co_git_essentials"],
  ["le_marcus", "co_linux"],
  ["le_marcus", "co_docker"],
  ["le_hana", "co_intro_programming"],
  ["le_hana", "co_html_css"],
  ["le_hana", "co_javascript"],
  ["le_hana", "co_react_fundamentals"],
  ["le_hana", "co_git_essentials"],
  ["le_omar", "co_intro_programming"],
  ["le_omar", "co_sql_essentials"],
  ["le_omar", "co_data_modeling"],
  ["le_omar", "co_databases_internals"],
  ["le_ines", "co_intro_programming"],
  ["le_ines", "co_html_css"],
  ["le_ines", "co_ui_design"],
];

module.exports = {
  skills,
  prereqEdges,
  instructors,
  courses,
  learners,
  hasSkill,
  completed,
};
